module.exports = {
  FETCH_FEATURES_INIT: 'FETCH_FEATURES_INIT',
  FETCH_FEATURES_FAILURE: 'FETCH_FEATURES_FAILURE',
  FETCH_FEATURES_SUCCESS: 'FETCH_FEATURES_SUCCESS',
  REGISTER_INIT: 'REGISTER_INIT',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_INIT: 'LOGIN_INIT',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  UPDATE_PAYLOAD: 'UPDATE_PAYLOAD',
  LOGOUT: 'LOGOUT',
};